### ISSUE TITLE
Prompt errors when no ruby version is specified for auto switching

### ISSUE THREAD

**Issue by mocoso** [JeanMertz/chruby-fish#30]
With chruby-fish (HEAD) installed I get the following error when cd'ing to any directory which is not home or a subdirectory of home

```
> cd /
fish: Unknown command 'grep'
/usr/local/Cellar/fish/2.6.0/share/fish/functions/grep.fish (line 1):
command grep --color=auto $argv
        ^
in function 'grep'
	called on line 36 of file /usr/local/Cellar/fish/2.6.0/share/fish/functions/seq.fish
	with parameter list '-E ^-?[0-9]*([0-9]*|\.[0-9]+)$'

in function '__fish_fallback_seq'
	called on line 7 of file /usr/local/Cellar/fish/2.6.0/share/fish/functions/seq.fish
	with parameter list '5'

in function 'seq'
	called on line 71 of file /usr/local/share/chruby/chruby.fish
	with parameter list '5'

in command substitution
	called on line 69 of file /usr/local/share/chruby/chruby.fish

in function 'chruby_reset'
	called on line 70 of file /usr/local/share/chruby/auto.fish

in function 'chruby_auto'
	called on standard input

in event handler: handler for generic event 'fish_prompt'

/usr/local/share/chruby/chruby.fish (line 18): Invalid index value
    set -q $unset_vars[$i]; and set -e $unset_vars[$i]; or true
                        ^
in function 'chruby_reset'
	called on line 70 of file /usr/local/share/chruby/auto.fish

in function 'chruby_auto'
	called on standard input

in event handler: handler for generic event 'fish_prompt'

fish: Unknown command 'hostname'
fish:
hostname|cut -d . -f 1
^
in command substitution
	called on standard input

in command substitution
	called on standard input
```

**Comment by mocoso** [comment]
This looks like a more general issue, which occurs anytime chruby is automatically switching back to the system ruby

**Comment by JeanMertz** [comment]
I'm not seeing what you are seeing:

```fish
~ ❯ cd /
/ ❯
/ ❯ chruby
   ruby-2.4.1
/ ❯ chruby ruby
/ ❯ chruby
 * ruby-2.4.1
/ ❯ chruby --version
chruby: 0.3.9
chruby-fish: 0.8.1
```

Could you validate that this is also happening for you on the latest stable version?

Also, looking at the error, there seems to be something wrong with your `PATH` variable, since the script can't find `grep` or `hostname`, which should always be present on your machine.

If you can reproduce the error, can you report back what `echo $PATH` and `grep --version` and `hostname` return?

**Comment by taralbass** [comment]
I saw this happen as well, but only when my .bashrc (or .bash_profile) happened to echo something. You can probably easily reproduce it by adding `echo "foo"` to an otherwise empty .bashrc. Then it looked to me like chruby-fish's chruby_reset ended up setting the path to 'foo' instead of the proper path, since foo ends up coming before the proper path in the output of the underlying call to chruby's chruby_reset.

**Comment by mocoso** [comment]
I can no longer reproduce this and so am closing the original issue.

@taralbass if you want to re-open it with the specific issue you found then please do.

**Comment by mthadley** [comment]
I'm running into the same original issue you had @mocoso. Do you happen to know what changes in your environment?
